# Generated by Django 4.2 on 2023-05-09 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tranfer',
            new_name='Transfer',
        ),
    ]
