# Generated by Django 4.2 on 2023-05-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customers_email_remove_customers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
